firm:
  public:
    controller: 'public'
    views:      'asrv'
    layout:     'asrv'
    page:
      title:        'Autoservice Ltd.'
      header:       'Autoservice motto'
      footer_text:  '&copy; 2005-2012 Autoservice Ltd.'
      footer_title: 'Ferenc-Loránt Kiss'
  system:
    page:
      title:        'TrustSys - Autoservice'
      header:       'TrustSys AutoServ'
      footer_text:  '&copy; 2005-2012 kfl62'
      footer_title: 'Ferenc-Loránt Kiss'

  sass_dir:     'system/assets/stylesheets/asrv'
  css_dir:      'public/stylesheets/asrv'
  images_dir:   'public/images/asrv'
  css_path:     '/stylesheets/asrv'
  images_path:  '/images/asrv'
  i18n_path:    'asrv'

  db_devel:     'trst_asrv'
  db_test:      'trst_test'
  db_prod:      'trst_asrv'
